
version: '3.8'

services:
  db:
    image: postgres
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      PGDATA: /database

  concourse:
    image: concourse/concourse
    command: web
    depends_on: [db]
    privileged: true
    ports: ["8080:8080"]
    volumes: ["./infra/keys/web:/concourse-keys"]
    environment:
      CONCOURSE_POSTGRES_HOST: ${DATABASE_HOST}
      CONCOURSE_POSTGRES_USER: ${DATABASE_USER}
      CONCOURSE_POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      CONCOURSE_POSTGRES_DATABASE: ${DATABASE}
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test

  concourse-worker:
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [concourse]
    volumes: ["./infra/keys/worker:/concourse-keys"]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: concourse:2222